name: Build Static Releases

on:
  release:
    types: [ created ]

jobs:
  build:
    name: Build static releases
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Build static release
        run: |
          CGO_ENABLED=0 go build --ldflags="-w -s" --output ./build/multipress

      - name: Upload Release Asset
        uses: csexton/release-asset-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          pattern: "build/*"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          release-url: ${{ steps.create_release.outputs.upload_url }}